### ISSUE TITLE
greek language

### ISSUE THREAD

**Issue by L1GHTNINGx** [lbphone/lb-phone-locales#105]
[el.json](https://github.com/user-attachments/files/15755162/el.json)

**Comment by brezedc** [comment]
Hey, please update it to the latest locale (check the en.json for reference), then create a pull-request!

**Comment by L1GHTNINGx** [comment]
thanks for notify I will when I'm back home!

Στις Σάβ 24 Αυγ 2024 στις 12:25 μ.μ., ο/η Breze ***@***.***>
έγραψε:
